import pytest
import pandas as pd
import numpy as np
import csv

@pytest.fixture(scope="module")
def fights_csv():
    f = open('C:/Users/danhm/PycharmProjects/UFCScraper/UFCScraper.csv', 'r')
    csvreader = csv.reader(f)
    return csvreader

@pytest.fixture(scope="module")
def test_headers(fights_csv):
    correct_headers = {"f_rd1_Body",
"f_rd1_Clinch",
"f_rd1_Ctrl",
f_rd1_Distance",
f_rd1_Ground",
f_rd1_Head",
f_rd1_KD",
f_rd1_Leg",
f_rd1_Rev",
f_rd1_Sig_str",
f_rd1_Sub_att",
f_rd1_Total_str",
f_rd2_Body",
f_rd2_Clinch",
f_rd2_Ctrl",
f_rd2_Distance",
f_rd2_Ground",
f_rd2_Head",
f_rd2_KD",
f_rd2_Leg",
f_rd2_Rev",
f_rd2_Sig_str",
f_rd2_Sub_att",
f_rd2_Total_str",
f_rd3_Body",
f_rd3_Clinch",
f_rd3_Ctrl",
f_rd3_Distance",
f_rd3_Ground",
f_rd3_Head",
f_rd3_KD",
f_rd3_Leg",
f_rd3_Rev",
f_rd3_Sig_str",
f_rd3_Sub_att",
f_rd3_Total_str",
f_rd4_Body",
f_rd4_Clinch",
f_rd4_Ctrl",
f_rd4_Distance",
f_rd4_Ground",
f_rd4_Head",
f_rd4_KD",
f_rd4_Leg",
f_rd4_Rev",
f_rd4_Sig_str",
f_rd4_Sub_att",
f_rd4_Total_str",
f_rd5_Body",
f_rd5_Clinch",
f_rd5_Ctrl",
f_rd5_Distance",
f_rd5_Ground",
f_rd5_Head",
f_rd5_KD",
f_rd5_Leg",
f_rd5_Rev",
f_rd5_Sig_str",
f_rd5_Sub_att",
f_rd5_Total_str",
o_rd1_Body",
o_rd1_Clinch",
o_rd1_Ctrl",
o_rd1_Distance",
o_rd1_Ground",
o_rd1_Head",
o_rd1_KD",
o_rd1_Leg",
o_rd1_Rev",
o_rd1_Sig_str",
o_rd1_Sub_att",
o_rd1_Total_str",
o_rd2_Body",
o_rd2_Clinch",
o_rd2_Ctrl",
o_rd2_Distance",
o_rd2_Ground",
o_rd2_Head",
o_rd2_KD",
o_rd2_Leg",
o_rd2_Rev",
o_rd2_Sig_str",
o_rd2_Sub_att",
o_rd2_Total_str",
o_rd3_Body",
o_rd3_Clinch",
o_rd3_Ctrl",
o_rd3_Distance",
o_rd3_Ground",
o_rd3_Head",
o_rd3_KD",
o_rd3_Leg",
o_rd3_Rev",
o_rd3_Sig_str",
o_rd3_Sub_att",
o_rd3_Total_str",
o_rd4_Body",
o_rd4_Clinch",
o_rd4_Ctrl",
o_rd4_Distance",
o_rd4_Ground",
o_rd4_Head",
o_rd4_KD",
o_rd4_Leg",
o_rd4_Rev",
o_rd4_Sig_str",
o_rd4_Sub_att",
o_rd4_Total_str",
o_rd5_Body",
o_rd5_Clinch",
o_rd5_Ctrl",
o_rd5_Distance",
o_rd5_Ground",
o_rd5_Head",
o_rd5_KD",
o_rd5_Leg",
o_rd5_Rev",
o_rd5_Sig_str",
o_rd5_Sub_att",
o_rd5_Total_str","
headers = next(fights_csv)
    return headers

